# Publish all joint states ------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Velocity Controllers ----------------------------------
  joint_left_back_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_back_wheel
    pid: {p: 0.1, i: 0.5, d: 0.1}

  joint_right_back_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_back_wheel
    pid: {p: 0.1, i: 0.5, d: 0.1}

  joint_left_front_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_front_wheel
    pid: {p: 0.1, i: 0.5, d: 0.1}

  joint_right_front_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_front_wheel
    pid: {p: 0.1, i: 0.5, d: 0.1}
